# IRC connection 
irc:
  host: '213.251.168.24'
  port: '6667'
  nick: irc_cat
  channel: '#irc_cat'

# HTTP Server

http:
  enabled: true
  host: 0.0.0.0
  port: '3489'
  github: true

# TCP Server

tcp:
  enabled: true
  host: 0.0.0.0
  port: '5678'