# IRC connection 
irc:
  host: 'irc.tty2.org'
  port: '6667'
  nick: irc_cat
  nick_pass: foo
  channel: '#irc_cat'
  channel_pass: bar
  # or:
  # channel: ['#one', '#two', '#three']
  # NB: the multichannel quickhack requires channel_pass to be hacked up. (not done (yet?))

# HTTP Server

http:
  enabled: true
  host: 0.0.0.0
  port: '3489'
  # Enable post-receive stuff from Github
  github: true
  # Allow send with http
  send: true

# TCP Server

tcp:
  enabled: true
  host: 0.0.0.0
  port: '5678'
  size: 400
